spring:
  redis:
    database: 0
    cluster:
      nodes:
      - 192.168.47.133:7000
      - 192.168.47.133:7001
      - 192.168.47.133:7002
      - 192.168.47.133:7003
      - 192.168.47.133:7004
      - 192.168.47.133:7005
      - 192.168.47.133:7006
      - 192.168.47.133:7007
      - 192.168.47.133:7008
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-idle: 10      # 连接池中的最大空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5       # 连接池中的最小空闲连接
        max-active: 100
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0        